sportovníAktivita1 = input("co jste dělal za sport: ")
sportovníAktivita2 = input("co jste dělal za druhý sport: ")
čas1 = int(input("kolik minut první sport: "))
čas2 = int(input("kolik minut druhý sport: "))
celkovy_vydej = ((čas1 + čas2) * 5)
print(celkovy_vydej)